package com.phraselog.analysis.dto;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.UUID;

/**
 * Fields to persist for a new {@code analysis_requests} row. {@code id} and {@code created_at} are
 * generated by the repository at insert time.
 *
 * <p>Exactly one of {@code userId}/{@code sessionToken} is set. {@code ipAddress} is populated only
 * for anonymous calls (pre-signup rate-limit audit) and is null for authenticated calls.
 */
public record NewAnalysis(
    UUID userId,
    String sessionToken,
    String ipAddress,
    String inputText,
    JsonNode outputJson,
    String promptVersion,
    UUID aiRequestLogId,
    UUID idempotencyKey) {}
