package com.phraselog.practice.dto;

import java.util.UUID;

/**
 * Fields to persist for a new roleplay session and its opening coach turn (#59). {@code id}/{@code
 * started_at}/{@code created_at} and the turn id are generated by the repository at insert time;
 * {@code status} is always {@code active} and the opening turn is {@code turn_number = 1}, {@code
 * speaker = coach}.
 */
public record NewPracticeSession(
    UUID userId,
    UUID expressionId,
    UUID coachId,
    int plannedTurns,
    UUID idempotencyKey,
    String openingText) {}
