#!/usr/bin/env bash
# harness-metrics.sh — 하니스/문서 계측 스냅샷 생성기
#
# 목적: 하니스 튜닝(커맨드/에이전트/훅/CLAUDE.md 구조 변경)의 효과를 before/after로
#       비교하기 위해, 동일한 방법으로 반복 측정 가능한 숫자를 뽑는다.
#       손으로 두 번 세면 비교가 성립하지 않으므로 측정은 반드시 이 스크립트로 한다.
#
# 사용: bash scripts/harness-metrics.sh            # 표준출력으로 markdown
#       bash scripts/harness-metrics.sh > out.md
#
# 주의: 토큰 수치는 전부 "추정"이다. 바이트가 1차 지표이고, 토큰은 한영 혼합
#       문서에 대한 대략치(bytes/3.5)로 절대 검증된 값이 아니다. 비교 목적으로만 쓴다.

set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

DEVLOGS="${DEVLOGS:-$HOME/Desktop/dev-logs}"

bytes() { # 존재하는 파일들의 합계 바이트
  local total=0 f sz
  for f in "$@"; do
    if [ -f "$f" ]; then
      sz=$(wc -c < "$f" | tr -d ' ')
      total=$((total + sz))
    fi
  done
  echo "$total"
}

est_tokens() { # 추정치 — 검증된 값 아님
  echo $(( $1 * 10 / 35 ))
}

echo "<!-- generated by scripts/harness-metrics.sh — do not hand-edit -->"
echo
echo "measured-at: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
echo "commit: $(git rev-parse --short HEAD 2>/dev/null || echo unknown)"
echo

# ---------------------------------------------------------------- 1. 컨텍스트 비용
ALWAYS="START_HERE.md CLAUDE.md AGENTS.md PROJECT_CONTEXT.md SECURITY.md docs/decisions/INDEX.md"

echo "## 1. 컨텍스트 비용 (항상 로드 세트)"
echo
echo "| file | bytes | est. tokens |"
echo "|---|---:|---:|"
for f in $ALWAYS; do
  [ -f "$f" ] || continue
  b=$(bytes "$f")
  printf '| `%s` | %s | ~%s |\n' "$f" "$b" "$(est_tokens "$b")"
done
A=$(bytes $ALWAYS)
printf '| **합계** | **%s** | **~%s** |\n' "$A" "$(est_tokens "$A")"
echo

# 티켓 작업 시 실제로 더 얹히는 것들
TICKET_EXTRA="docs/harness.md docs/quality-gates.md .claude/commands/ticket-start.md"
echo "### 티켓 1건 시작 시 실제 로드"
echo
echo "항상 로드 세트에 더해 \`/ticket-start\` 체인이 끌어오는 문서:"
echo
echo "| file | bytes |"
echo "|---|---:|"
for f in $TICKET_EXTRA; do
  [ -f "$f" ] || continue
  printf '| `%s` | %s |\n' "$f" "$(bytes "$f")"
done
E=$(bytes $TICKET_EXTRA)
# 화면 스펙 평균 1건
SCR_N=$(ls docs/screens/*.md 2>/dev/null | wc -l | tr -d ' ')
SCR_B=$(cat docs/screens/*.md 2>/dev/null | wc -c | tr -d ' ')
SCR_AVG=0
[ "${SCR_N:-0}" -gt 0 ] && SCR_AVG=$((SCR_B / SCR_N))
printf '| 화면 스펙 1건 (평균, n=%s) | %s |\n' "$SCR_N" "$SCR_AVG"
T=$((A + E + SCR_AVG))
printf '| **티켓 1건 총 로드** | **%s** (~%s tokens 추정) |\n' "$T" "$(est_tokens "$T")"
echo

# ---------------------------------------------------------------- 2. 하니스 자산
echo "## 2. 하니스 자산 인벤토리"
echo
CMD_N=$(ls .claude/commands/*.md 2>/dev/null | wc -l | tr -d ' ')
AGT_N=$(ls .claude/agents/*.md 2>/dev/null | wc -l | tr -d ' ')
SKL_N=$(ls -d .claude/skills/*/ 2>/dev/null | wc -l | tr -d ' ')
HOOK_N=$(grep -c '"type": *"command"' .claude/settings.json 2>/dev/null || echo 0)
HOOK_EV=$(grep -oE '"(PreToolUse|PostToolUse|PermissionRequest|Stop|SubagentStop|Notification|UserPromptSubmit|SessionStart)"' .claude/settings.json 2>/dev/null | sort -u | wc -l | tr -d ' ')
ALLOW_N=$(grep -cE '^\s*"(Bash\(|mcp__)' .claude/settings.json 2>/dev/null || echo 0)
echo "| 항목 | 수 |"
echo "|---|---:|"
echo "| slash command | $CMD_N |"
echo "| subagent | $AGT_N |"
echo "| skill | $SKL_N |"
echo "| hook (command 개수) | $HOOK_N |"
echo "| hook (걸린 이벤트 종류) | $HOOK_EV |"
echo "| permission allow 규칙 | $ALLOW_N |"
echo

# ---------------------------------------------------------------- 3. 문서 규모/무결성
echo "## 3. 문서 규모와 무결성"
echo
DOC_N=$(find docs -name '*.md' 2>/dev/null | wc -l | tr -d ' ')
DOC_B=$(find docs -name '*.md' -exec cat {} + 2>/dev/null | wc -c | tr -d ' ')
ADR_N=$(ls docs/decisions/[0-9]*.md 2>/dev/null | wc -l | tr -d ' ')
ADR_IDX=$(grep -cE '^\| [0-9]{3} \|' docs/decisions/INDEX.md 2>/dev/null || echo 0)
TBD_N=$(grep -rho 'TBD' docs 2>/dev/null | wc -l | tr -d ' ')
PLAN_N=$(ls docs/exec-plans/*.md 2>/dev/null | wc -l | tr -d ' ')
REV_N=$(ls docs/reviews/*.md 2>/dev/null | wc -l | tr -d ' ')
echo "| 항목 | 값 |"
echo "|---|---:|"
echo "| docs/*.md 파일 수 | $DOC_N |"
echo "| docs 총 바이트 | $DOC_B |"
echo "| ADR 파일 수 | $ADR_N |"
echo "| ADR INDEX 행 수 | $ADR_IDX |"
echo "| ADR 인덱스 동기 (같으면 OK) | $([ "$ADR_N" = "$ADR_IDX" ] && echo OK || echo DRIFT) |"
echo "| TBD 총 개수 | $TBD_N |"
echo "| exec-plan 수 | $PLAN_N |"
echo "| review 수 | $REV_N |"
echo

echo "### 깨진 상대 링크"
echo
python - <<'PY' 2>/dev/null || echo "(python 없음 — 링크 검사 생략)"
import re, os, glob
bad = []
for f in glob.glob('**/*.md', recursive=True):
    if '.git' in f or 'node_modules' in f:
        continue
    try:
        t = open(f, encoding='utf-8', errors='replace').read()
    except Exception:
        continue
    for m in re.finditer(r'\]\(([^)#:]+\.md)(#[^)]*)?\)', t):
        p = m.group(1).strip()
        if p.startswith('http'):
            continue
        tgt = os.path.normpath(os.path.join(os.path.dirname(f), p))
        if not os.path.exists(tgt):
            bad.append((f, p))
print("broken-links:", len(bad))
for f, p in bad[:30]:
    print("  -", f, "->", p)
PY
echo

# ---------------------------------------------------------------- 4. 리뷰 재작업률
echo "## 4. 2게이트 리뷰 재작업률"
echo
if [ "$REV_N" -gt 0 ]; then
  RW=$(grep -rliE '재작업|blocker|반려|must fix|조건부|needs work' docs/reviews/*.md 2>/dev/null | wc -l | tr -d ' ')
  echo "| 항목 | 값 |"
  echo "|---|---:|"
  echo "| 리뷰 총 건수 | $REV_N |"
  echo "| 재작업/블로커 언급 건수 | $RW |"
  echo "| 재작업률 | $((RW * 100 / REV_N))% |"
else
  echo "(docs/reviews 없음)"
fi
echo

# ---------------------------------------------------------------- 5. 세션 마찰
echo "## 5. 세션 마찰 (dev-logs)"
echo
if [ -d "$DEVLOGS" ]; then
  LOG_N=$(ls "$DEVLOGS"/*.md 2>/dev/null | wc -l | tr -d ' ')
  FRIC=$(grep -rliE '드리프트|drift|중복|불일치|harness|ticket-start|롤백|rollback|incident|사고|재작업|dangling|충돌' "$DEVLOGS"/*.md 2>/dev/null | wc -l | tr -d ' ')
  ERR=$(grep -rliE '에러|error|실패|failed|traceback' "$DEVLOGS"/*.md 2>/dev/null | wc -l | tr -d ' ')
  MAINT=$(ls "$DEVLOGS" 2>/dev/null | grep -icE 'harness|ticket-start|drift|dedup|doc-|claude-md|ledger|protocol|guardrail|hook|skill|command|index|incident|rollback|cleanup|audit' | tr -d ' ')
  echo "| 항목 | 값 |"
  echo "|---|---:|"
  echo "| dev-log 총 세션 수 | $LOG_N |"
  echo "| 하니스/문서 마찰 언급 세션 | $FRIC ($((FRIC * 100 / LOG_N))%) |"
  echo "| 에러/실패 언급 세션 | $ERR ($((ERR * 100 / LOG_N))%) |"
  echo "| 제목부터 정비 작업인 세션 | $MAINT ($((MAINT * 100 / LOG_N))%) |"
else
  echo "(dev-logs 디렉터리 없음: $DEVLOGS)"
fi
echo

echo "## 6. 열린 티켓"
echo
if command -v gh >/dev/null 2>&1; then
  OPEN=$(gh issue list --state open --limit 200 2>/dev/null | wc -l | tr -d ' ')
  echo "열린 이슈: $OPEN"
else
  echo "(gh 없음)"
fi
